#include "instructions.h"

void (* const opcodes[256])(void) = {
    NOP,        // 0
    NOP,        // 1
    NOP,        // 2
    NOP,        // 3
    NOP,        // 4
    NOP,        // 5
    ASL_Z,        // 6
    NOP,        // 7
    NOP,        // 8
    NOP,        // 9
    ASL,        // 10
    NOP,        // 11
    NOP,        // 12
    NOP,        // 13
    ASL_A,        // 14
    NOP,        // 15
    NOP,        // 16
    NOP,        // 17
    NOP,        // 18
    NOP,        // 19
    NOP,        // 20
    NOP,        // 21
    ASL_ZX,        // 22
    NOP,        // 23
    NOP,        // 24
    NOP,        // 25
    NOP,        // 26
    NOP,        // 27
    NOP,        // 28
    NOP,        // 29
    ASL_AX,        // 30
    NOP,        // 31
    NOP,        // 32
    AND_IX,        // 33
    NOP,        // 34
    NOP,        // 35
    NOP,        // 36
    AND_Z,        // 37
    NOP,        // 38
    NOP,        // 39
    NOP,        // 40
    AND_I,        // 41
    NOP,        // 42
    NOP,        // 43
    NOP,        // 44
    AND_A,        // 45
    NOP,        // 46
    NOP,        // 47
    NOP,        // 48
    AND_IY,        // 49
    NOP,        // 50
    NOP,        // 51
    NOP,        // 52
    AND_ZX,        // 53
    NOP,        // 54
    NOP,        // 55
    NOP,        // 56
    AND_AY,        // 57
    NOP,        // 58
    NOP,        // 59
    NOP,        // 60
    AND_AX,        // 61
    NOP,        // 62
    NOP,        // 63
    NOP,        // 64
    NOP,        // 65
    NOP,        // 66
    NOP,        // 67
    NOP,        // 68
    NOP,        // 69
    NOP,        // 70
    NOP,        // 71
    NOP,        // 72
    NOP,        // 73
    NOP,        // 74
    NOP,        // 75
    NOP,        // 76
    NOP,        // 77
    NOP,        // 78
    NOP,        // 79
    NOP,        // 80
    NOP,        // 81
    NOP,        // 82
    NOP,        // 83
    NOP,        // 84
    NOP,        // 85
    NOP,        // 86
    NOP,        // 87
    NOP,        // 88
    NOP,        // 89
    NOP,        // 90
    NOP,        // 91
    NOP,        // 92
    NOP,        // 93
    NOP,        // 94
    NOP,        // 95
    NOP,        // 96
    ADC_IX,        // 97
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    ADC_Z,        // 101
    NOP,        // 102
    NOP,        // 103
    NOP,        // 104
    ADC_I,        // 105
    NOP,        // 106
    NOP,        // 107
    NOP,        // 108
    ADC_A,        // 109
    NOP,        // 110
    NOP,        // 111
    NOP,        // 112
    ADC_IY,        // 113
    NOP,        // 114
    NOP,        // 115
    NOP,        // 116
    ADC_ZX,        // 117
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    ADC_AY,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    ADC_AX,        // 125
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP,        // 0
    NOP         // 255
};